---
# File: playbook.yml
# Web Servers
- hosts: webserver
  become: yes
  become_method: sudo
  roles:
    - systools
    - apache2
    - php5-fpm
    - mysql
    - phpmyadmin
    - composer
  
# - hosts: ilias
#   become: yes
#   become_method: sudo
#   roles:
#     - InstILIAS

- hosts: generali
  become: yes
  become_method: sudo
  roles:
    - catILIAS