---
# File: roles/InstILIAS/tasks/main.yml
# Clone InstILIAS to /var/www/default

- name: git | get InstILIAS
  git:  repo=git://github.com/conceptsandtraining/InstILIAS.git dest=/home/vagrant/share/repos

- name: file | copy InstILIAS config file
  copy:
    src:  ../templates/config.yml
    dest: /home/vagrant/share/